/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconClose: typeof import('~icons/ic/on-close')['default']
    IconsArrowRight: typeof import('~icons/icons/arrow-right')['default']
    IconsAvatar: typeof import('~icons/icons/avatar')['default']
    IconsCalendar: typeof import('~icons/icons/calendar')['default']
    IconsCat: typeof import('~icons/icons/cat')['default']
    IconsClock: typeof import('~icons/icons/clock')['default']
    IconsClose: typeof import('~icons/icons/close')['default']
    IconsCreditCard: typeof import('~icons/icons/credit-card')['default']
    IconsDatePicker: typeof import('~icons/icons/date-picker')['default']
    IconsHome: typeof import('~icons/icons/home')['default']
    IconsLogo: typeof import('~icons/icons/logo')['default']
    IconsLogout: typeof import('~icons/icons/logout')['default']
    IconsLogOut: typeof import('~icons/icons/log-out')['default']
    IconsMessage: typeof import('~icons/icons/message')['default']
    IconsNotification: typeof import('~icons/icons/notification')['default']
    IconsNotificationBg: typeof import('~icons/icons/notification-bg')['default']
    IconsNotifications: typeof import('~icons/icons/notifications')['default']
    IconsPlus: typeof import('~icons/icons/plus')['default']
    IconsPLus: typeof import('~icons/icons/p-lus')['default']
    IconsSchedule: typeof import('~icons/icons/schedule')['default']
    IconsSearch: typeof import('~icons/icons/search')['default']
    IconsSettings: typeof import('~icons/icons/settings')['default']
    IconsSupport: typeof import('~icons/icons/support')['default']
    IconsUser: typeof import('~icons/icons/user')['default']
    IconsWorld: typeof import('~icons/icons/world')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
