/* EDIT CAREFULLY! GENERATED AUTOMATICALLY! */
export default {
  neutral: {
    ultralight: '#F0F0F0',
    gray: '#F2F2F2',
    light: '#C8C8C8',
    dark: '#575756',
    black: '#000000',
    white: '#FFFFFF',
    beige: '#F3F2F2',
  },
  transparent: 'transparent',
  inherit: 'inherit',
  'background-secondary': 'var(--colorBackgroundSecondary)',
  'background-primary': 'var(--colorBackgroundPrimary)',
  'background-deselected': 'var(--colorBackgroundDeselected)',
  'stroke-card': 'var(--colorStrokeCard)',
  'stroke-inactive': 'var(--colorStrokeInactive)',
  'stroke-primary': 'var(--colorStrokePrimary)',
  'stroke-deselected': 'var(--colorStrokeDeselected)',
  'icon-wishlist': 'var(--colorIconWishlist)',
  'icon-primary': 'var(--colorIconPrimary)',
  'icon-secondary': 'var(--colorIconSecondary)',
  'icon-tertiary': 'var(--colorIconTertiary)',
  'icon-deselected': 'var(--colorIconDeselected)',
  'text-primary': 'var(--colorTextPrimary)',
  'text-inactive': 'var(--colorTextInactive)',
  'text-tertiary': 'var(--colorTextTertiary)',
  'text-secondary': 'var(--colorTextSecondary)',
  primitives: {
    'off-white': '#fbfbfb',
    black: '#000000',
    white: '#ffffff',
    blue: '#2f6eb4',
    orange: '#fa7600',
    'grey-50': '#f2f2f2',
    'grey-100': '#ebebeb',
    'grey-200': '#999999',
    'grey-150': '#d9d9d9',
    'grey-300': '#4b4b4b',
    red: '#ff002e',
    green: '#38d17e',
    'white-10': 'rgba(255, 255, 255, 0.1)',
    'black-5': 'rgba(0, 0, 0, 0.05)',
    'white-80': 'rgba(255, 255, 255, 0.8)',
    'black-80': 'rgba(0, 0, 0, 0.8)',
    'black-60': 'rgba(0, 0, 0, 0.6)',
  },
  'background-deselected-light': 'var(--colorBackgroundDeselectedLight)',
  'background-tertiary': 'var(--colorBackgroundTertiary)',
  'stroke-card-default': 'var(--colorStrokeCardDefault)',
  background: 'var(--colorBackground)',
}
