/* DO NOT EDIT THIS FILE, IT WAS GENERATED AUTOMATICALLY! */
import plugin from 'tailwindcss/plugin'

export default plugin(({ addComponents }) => {
  addComponents({
    '.grid-l-1920': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '1.5rem',
      justifyItems: 'stretch',
      paddingLeft: '4rem',
      paddingRight: '4rem',
    },
    '.grid-l-1280': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '1rem',
      justifyItems: 'stretch',
      paddingLeft: '3rem',
      paddingRight: '3rem',
    },
    '.grid-m-1279': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '1rem',
      justifyItems: 'stretch',
      paddingLeft: '3rem',
      paddingRight: '3rem',
    },
    '.grid-m-768': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '1rem',
      justifyItems: 'stretch',
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
    '.grid-s-767': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '1rem',
      justifyItems: 'stretch',
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
    '.grid-s-375': {
      display: 'grid',
      gridTemplateColumns: 'repeat(12, minmax(0, 1fr))',
      gridGap: '0.5rem',
      justifyItems: 'stretch',
      paddingLeft: '1rem',
      paddingRight: '1rem',
    },
  })
})
